Muzima 597 - ErrorMessage Search
muzima/openmrs-module-muzimacore pull request #29
Opened 2018-06-30 17:49 UTC by milankarunarathne

Improve Error search with ErrorMessage content.
- Include ErrorMessage  Ids while searching for Errors.

2018-07-01 05:36 UTC, mssavai requested changes
Please review to address two issues raised.

Thanks

2018-07-01 05:36 UTC, mssavai commented on api/src/main/java/org/openmrs/module/muzima/api/service/impl/DataServiceImpl.java
> +            if (StringUtils.contains(errorMessage.getMessage(), search)){
Can this be made non case sensitive? That way it will be more usable.

2018-07-01 05:36 UTC, mssavai commented on api/src/main/java/org/openmrs/module/muzima/api/db/hibernate/HibernateDataDao.java
> +		        disjunction.add(Restrictions.in("id", errorIds));
Kindly review this. You are comparing ErrorData.id against ErrorMessage.id, which are not equivalent.

2018-07-02 23:47 UTC, milankarunarathne commented
I have added those changes on to the pull request, please review it.

2019-01-21 08:22 UTC, mssavai commented
Closing as this is no longer needed as the update has already been done and merged

2019-01-21 08:22 UTC, closed without merging